server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: make
          uri: http://localhost:8082
          predicates:
            - Path=/makes/** 
        - id: complete
          uri: http://localhost:8083
          predicates:
            - Path=/completes/**
        - id: showStatus
          uri: http://localhost:8084
          predicates:
            - Path=/showStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/** 
        - id: make
          uri: http://make:8080
          predicates:
            - Path=/makes/** 
        - id: complete
          uri: http://complete:8080
          predicates:
            - Path=/completes/**
        - id: showStatus
          uri: http://showStatus:8080
          predicates:
            - Path=/showStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
